#include "vr/vrcontrols.h"
#include "vr/vrwelcome.h"
#include "vr/vrprofiler.h"
#include "vr/xrmath.h"
#include "vr/vrroomscale.h"
#include <cstdio>
#include <cstdlib>
#include <sstream>
#include <limits>
#include <filesystem>
static int checks=0;
static void test(bool pass,const char* name) { ++checks; if(!pass) { std::fprintf(stderr,"FAIL %s\n",name); std::exit(1); } }
static void close(float a,float b,const char* name) { test(std::abs(a-b)<0.003f,name); }
int main() {
  Vr::Settings settings; test(settings.indexedObjects,"indexed geometry enabled for old settings"); test(settings.fastLighting,"new lighting enabled for old settings files");
  test(settings.batchedObjects,"object batching defaults on");
  test(settings.shadows && settings.lighting && settings.localLights,"render tests default to full rendering");
  Vr::Settings legacy; std::istringstream legacyIni("IndexedObjects=0\n"); legacy.read(legacyIni);
  test(legacy.batchedObjects && !legacy.indexedObjects,"old INI enables batching without changing indexed preference");
  Vr::Settings legacyIndexed; std::istringstream legacyIndexedIni("IndexedObjects=1\n"); legacyIndexed.read(legacyIndexedIni);
  test(legacyIndexed.batchedObjects && legacyIndexed.indexedObjects,"014 INI migrates to batching without rewriting geometry preference");
  test(legacy.frameOverlap,"old INI enables CPU/GPU overlap");
  test(legacy.tiledLights,"old INI enables tiled local lights");
  test(legacy.subgroupTiles && legacy.uniformLights && legacy.stereoSeed && legacy.framePipeline,"old INI enables subgroup and stereo preparation");
  test(legacy.shadows && legacy.lighting && legacy.localLights,"old INI keeps all render passes enabled");
  test(legacy.directOutput,"018 settings default On in old INI");
  test(legacy.slabLights,"019 light slabs default On in old INI");
  { Vr::Settings tilesOff; std::istringstream ini("TiledLights=0\nSlabLights=0\n"); tilesOff.read(ini); test(!tilesOff.slabLights && !tilesOff.tiledLights,"SlabLights=0 keeps the previous tile preference"); }
  std::istringstream corrupt("WorldScale=nan\nRenderScale=inf\nSmoothSpeed=999\nSnapAngle=-3\nTurnMode=9\nHudDistance=-50\nUnknown=123\n");
  settings.read(corrupt);
  close(settings.worldScale,1,"NaN scale rejected"); close(settings.renderScale,1,"infinite render scale rejected");
  test(settings.smoothSpeed==180,"smooth speed upper bound"); test(settings.snapAngle==15,"snap angle lower bound");
  test(settings.turn==Vr::TurnMode::Snap,"invalid turn mode"); close(settings.hudDistance,1,"HUD distance lower bound");
  settings.worldScale=1.35f; settings.renderScale=0.75f; settings.turn=Vr::TurnMode::Smooth; settings.roomScale=false;
  std::ostringstream saved; settings.write(saved); Vr::Settings restored; std::istringstream input(saved.str()); restored.read(input);
  close(restored.worldScale,1.35f,"world scale round trip"); close(restored.renderScale,0.75f,"render scale round trip");
  test(restored.turn==Vr::TurnMode::Smooth && !restored.roomScale,"mode round trip");
  Vr::Menu menu; Vr::Input in; in.focused=true; uint64_t now=0;
  auto step=[&] { now+=20; return menu.update(in,now); };
  auto release=[&] { in={}; in.focused=true; step(); };
  test(step(),"first neutral input is consumed"); test(!step(),"gameplay after neutral");
  in.leftGrip=in.rightGrip=in.menu=true;
  test(step()&&menu.visible,"chord opens VR menu and consumes input");
  test(step()&&menu.visible,"held chord cannot retoggle"); release();
  test(menu.rows().size()==11 && menu.row()==Vr::Menu::Locomotion,"main menu exposes submenus");
  in.a=true; step(); test(menu.page==Vr::Menu::Page::Locomotion&&!menu.changed,"A enters locomotion without changing settings");
  step(); test(menu.settings.turn==Vr::TurnMode::Snap,"held A on entry cannot change turn mode"); release();
  in.a=true; step(); test(menu.settings.turn==Vr::TurnMode::Smooth && menu.changed,"A changes selected setting");
  step(); test(!menu.changed,"held A cannot repeat setting change"); release();
  in.y=1; step(); test(menu.selected==1,"stick selects next row");
  step(); test(menu.selected==1,"repeat delayed"); now+=420; step(); test(menu.selected==2,"held navigation repeats"); release();
  in.b=true; step(); test(menu.page==Vr::Menu::Page::Main&&menu.visible,"B returns from submenu without closing VR menu");
  step(); test(menu.visible,"held B cannot close parent"); release();
  in.y=1; step(); release(); in.a=true; step();
  test(menu.page==Vr::Menu::Page::Hud,"HUD submenu reachable with controls"); release();
  menu.selected=4; in.x=1; step(); close(menu.settings.hudX,0.025f,"HUD shifts right in 2.5 percent steps");
  test(menu.changed&&!menu.recenter,"HUD offset saves without recentering world"); release();
  in.y=1; step(); release(); in.x=-1; step(); close(menu.settings.hudY,-0.025f,"HUD vertical adjustment"); release();
  in.y=1; step(); release(); in.a=true; step(); close(menu.settings.hudX,0,"HUD reset horizontal"); close(menu.settings.hudY,0,"HUD reset vertical"); release();
  in.b=true; step(); release(); in.b=true; step(); test(!menu.visible,"B closes root menu");
  test(step(),"held close cannot reach game"); in.b=false; in.x=1; test(step(),"movement blocked until neutral");
  release(); test(!step(),"gameplay resumes after neutral");
  in.focused=false; test(step(),"focus loss consumes input");
  in.focused=true; in.leftGrip=in.rightGrip=in.menu=true; step(); test(!menu.visible,"held chord across focus gain cannot open menu");
  release(); in.leftGrip=in.rightGrip=in.menu=true; step(); test(menu.visible,"released chord works after focus gain"); release();
  in.a=true; step(); release(); menu.selected=3; in.x=1; step();
  test(menu.changed&&menu.recenter,"scale change requests recenter"); close(menu.settings.worldScale,1.05f,"scale step"); release();
  in.b=true; step(); release(); menu.selected=2; in.a=true; step(); release();
  test(menu.page==Vr::Menu::Page::Performance,"performance submenu reachable"); menu.selected=1; in.a=true; step(); test(menu.settings.fogMode==1,"fog comparison mode changes"); release();
  menu.selected=3; in.a=true; step(); test(menu.settings.gpuSampling==2,"every-frame GPU measurement selectable");
  release(); menu.selected=4; in.a=true; step(); test(!menu.settings.fastLighting && menu.changed,"lighting comparison reachable and saves");
  step(); test(!menu.settings.fastLighting && !menu.changed,"held accept cannot toggle lighting repeatedly"); release();
  menu.selected=5; in.a=true; step(); test(!menu.settings.indexedObjects && menu.changed,"geometry comparison is reachable"); release();
  menu.selected=6; in.a=true; step();
  test(!menu.settings.batchedObjects && !menu.settings.indexedObjects && menu.changed,"batching comparison toggles independently");
  step(); test(!menu.settings.batchedObjects && !menu.changed,"held accept cannot repeat batching toggle"); release();
  in.trigger=1; step(); test(menu.settings.batchedObjects && !menu.settings.indexedObjects && menu.changed,"trigger restores batching without changing indexed preference"); release();
  menu.selected=9; in.trigger=1; step();
  test(!menu.settings.directOutput && menu.changed,"Direct output toggles");
  step(); test(!menu.settings.directOutput && !menu.changed,"Held trigger does not retoggle direct output"); release();
  std::ostringstream modeIni; menu.settings.write(modeIni); Vr::Settings modeRestored; std::istringstream modeInput(modeIni.str()); modeRestored.read(modeInput);
  test(!modeRestored.directOutput && modeRestored.shadows,"018 switches persist without resetting old preferences");
  menu.selected=12; in.x=1; step();
  test(menu.row()==Vr::Menu::Horizon && menu.settings.horizon==2 && menu.changed && !menu.recenter,"Horizon steps from 450 m to 600 m without recentering");
  step(); test(menu.settings.horizon==2 && !menu.changed,"held stick cannot repeat horizon step"); release();
  in.x=-1; step(); release(); in.x=-1; step(); test(menu.settings.horizon==0 && menu.changed,"Horizon steps down to 300 m"); release();
  in.x=-1; step(); test(menu.settings.horizon==3,"Horizon wraps to 1 km"); release();
  in.x=1; step(); test(menu.settings.horizon==0,"Horizon wraps back to 300 m"); release();
  std::ostringstream horizonIni; menu.settings.write(horizonIni); Vr::Settings horizonRestored; std::istringstream horizonInput(horizonIni.str()); horizonRestored.read(horizonInput);
  test(horizonRestored.horizon==0 && !horizonRestored.directOutput && horizonRestored.horizonHaze,"Horizon persists with existing preferences");
  std::istringstream invalidHorizon("Horizon=9\n"); horizonRestored.read(invalidHorizon); test(horizonRestored.horizon==3,"out-of-range horizon clamps to 1 km");
  std::istringstream oldHorizon("HorizonHaze=1\n"); Vr::Settings oldRestored; oldRestored.read(oldHorizon); test(oldRestored.horizon==1,"old INI defaults the horizon to 450 m");
  in.x=1; step(); release(); test(menu.settings.horizon==1,"Horizon returns to the default 450 m");
  menu.selected=13; in.a=true; step();
  test(menu.page==Vr::Menu::Page::Power && menu.rows().size()==3 && menu.row()==Vr::Menu::CpuLevel && !menu.changed,"Power submenu opens on CPU level");
  release(); in.x=-1; step();
  test(menu.settings.cpuLevel==3 && menu.settings.gpuLevel==4 && menu.changed && !menu.recenter,"CPU level steps from Boost to Sustained high independently");
  step(); test(menu.settings.cpuLevel==3 && !menu.changed,"held stick cannot repeat CPU level step"); release();
  in.x=1; step(); release(); in.x=1; step(); release(); test(menu.settings.cpuLevel==0,"CPU level wraps to Runtime default");
  in.x=-1; step(); release(); test(menu.settings.cpuLevel==4,"CPU level wraps back to Boost");
  in.y=1; step(); release(); in.x=-1; step(); release();
  test(menu.row()==Vr::Menu::GpuLevel && menu.settings.gpuLevel==3 && menu.settings.cpuLevel==4,"GPU level steps independently of CPU");
  in.x=-1; step(); release(); in.x=-1; step(); release(); test(menu.settings.gpuLevel==1,"GPU level reaches Power savings");
  std::ostringstream powerIni; menu.settings.write(powerIni); Vr::Settings powerRestored; std::istringstream powerInput(powerIni.str()); powerRestored.read(powerInput);
  test(powerRestored.cpuLevel==4 && powerRestored.gpuLevel==1 && powerRestored.horizon==1,"CPU and GPU levels persist with the horizon");
  std::istringstream invalidPower("CpuLevel=9\nGpuLevel=-2\n"); powerRestored.read(invalidPower); test(powerRestored.cpuLevel==4 && powerRestored.gpuLevel==0,"out-of-range levels clamp");
  std::istringstream oldPower("PowerMode=2\n"); Vr::Settings migrated; migrated.read(oldPower); test(migrated.cpuLevel==4 && migrated.gpuLevel==4,"026 PowerMode=2 migrates to Boost/Boost");
  std::istringstream oldSustained("PowerMode=1\n"); migrated.read(oldSustained); test(migrated.cpuLevel==3 && migrated.gpuLevel==3,"026 PowerMode=1 migrates to Sustained high");
  test(Vr::Settings().cpuLevel==4 && Vr::Settings().gpuLevel==4 && !Vr::Settings().earlyLeftEye && Vr::Settings().horizon==1,"026 defaults: Boost power, early left eye off, 450 m horizon");
  in.x=1; step(); release(); in.x=1; step(); release(); in.x=1; step(); release(); test(menu.settings.gpuLevel==4,"GPU level restored to Boost");
  in.y=1; step(); release(); in.a=true; step(); release();
  test(menu.page==Vr::Menu::Page::Performance && menu.row()==Vr::Menu::Power && !menu.changed,"Back returns to the Power row");
  menu.selected=14; in.x=1; step();
  test(menu.row()==Vr::Menu::TerrainLod && menu.settings.terrainLod==3 && menu.changed,"Terrain detail steps from Near to Aggressive");
  step(); test(menu.settings.terrainLod==3 && !menu.changed,"held stick cannot repeat terrain detail step"); release();
  in.x=1; step(); release(); test(menu.settings.terrainLod==0,"Terrain detail wraps to Full");
  in.x=-1; step(); release(); test(menu.settings.terrainLod==3,"Terrain detail wraps back to Aggressive");
  in.x=-1; step(); release(); test(menu.settings.terrainLod==2,"Terrain detail returns to Near");
  std::ostringstream lodIni; menu.settings.write(lodIni); Vr::Settings lodRestored; std::istringstream lodInput(lodIni.str()); lodRestored.read(lodInput);
  test(lodRestored.terrainLod==2 && lodRestored.cpuLevel==4,"Terrain detail persists with the power levels");
  std::istringstream invalidLod("TerrainLod=9\n"); lodRestored.read(invalidLod); test(lodRestored.terrainLod==3,"out-of-range terrain detail clamps");
  std::istringstream oldLod("Horizon=1\n"); Vr::Settings oldLodRestored; oldLodRestored.read(oldLod); test(oldLodRestored.terrainLod==2,"old INI defaults terrain detail to Near");
  menu.selected=15; in.x=1; step();
  test(menu.row()==Vr::Menu::Foveation && menu.settings.foveation==1 && menu.changed,"Foveation steps from Off to Low");
  step(); test(menu.settings.foveation==1 && !menu.changed,"held stick cannot repeat foveation step"); release();
  in.x=-1; step(); release(); test(menu.settings.foveation==0,"Foveation steps back to Off");
  in.x=-1; step(); release(); test(menu.settings.foveation==3,"Foveation wraps to High");
  in.x=1; step(); release(); test(menu.settings.foveation==0,"Foveation wraps back to Off");
  std::ostringstream fovIni; menu.settings.write(fovIni); Vr::Settings fovRestored; std::istringstream fovInput(fovIni.str()); fovRestored.read(fovInput);
  test(fovRestored.foveation==0 && fovRestored.terrainLod==2,"Foveation persists with terrain detail");
  std::istringstream invalidFov("FoveationBands=7\n"); fovRestored.read(invalidFov); test(fovRestored.foveation==3,"out-of-range foveation clamps");
  std::istringstream oldFov("Foveation=2\n"); Vr::Settings oldFovRestored; oldFovRestored.read(oldFov); test(oldFovRestored.foveation==0,"the 0.0.28 Foveation key is ignored: off");
  std::istringstream bandFov("FoveationBands=2\n"); oldFovRestored.read(bandFov); test(oldFovRestored.foveation==2,"FoveationBands restores");
  menu.selected=16; in.x=1; step();
  test(menu.row()==Vr::Menu::StaticLighting && !menu.settings.staticLighting && menu.changed,"Lighting toggles from 2002 static to Dynamic");
  step(); test(!menu.settings.staticLighting && !menu.changed,"held stick cannot repeat the lighting toggle"); release();
  in.x=-1; step(); release(); test(menu.settings.staticLighting,"Lighting toggles back to 2002 static");
  std::ostringstream slIni; menu.settings.write(slIni); Vr::Settings slRestored; slRestored.staticLighting=false; std::istringstream slInput(slIni.str()); slRestored.read(slInput);
  test(slRestored.staticLighting && slRestored.foveation==0,"Lighting mode persists with foveation");
  std::istringstream oldSl("FoveationBands=0\n"); Vr::Settings oldSlRestored; oldSlRestored.read(oldSl); test(oldSlRestored.staticLighting,"old INI defaults to 2002 static lighting");
  std::istringstream offSl("StaticLighting=0\n"); oldSlRestored.read(offSl); test(!oldSlRestored.staticLighting,"StaticLighting=0 restores Dynamic");
  menu.selected=17; in.a=true; step(); release();
  test(menu.page==Vr::Menu::Page::Main && menu.selected==2,"performance Back row is the last row and returns to the Performance entry");
  in.a=true; step(); release(); test(menu.page==Vr::Menu::Page::Performance,"performance submenu reopened");
  menu.selected=8; in.a=true; step();
  test(menu.page==Vr::Menu::Page::RenderTests && menu.rows().size()==14 && !menu.changed,"render tests opens without changing settings");
  test(menu.row()==Vr::Menu::Shadows,"render tests starts with shadows");
  step(); test(menu.settings.shadows && !menu.changed,"held accept entering render tests cannot toggle shadows"); release();
  in.a=true; step(); test(!menu.settings.shadows && menu.settings.lighting && menu.settings.localLights && menu.changed,"shadows toggles independently and saves");
  step(); test(!menu.settings.shadows && !menu.changed,"held accept does not retoggle shadows"); release();
  menu.selected=1; in.trigger=1; step(); test(!menu.settings.lighting && !menu.settings.shadows && menu.settings.localLights && menu.changed,"trigger selects unlit independently");
  step(); test(!menu.settings.lighting && !menu.changed,"held trigger does not repeat lighting toggle"); release();
  menu.selected=2; in.x=-1; step(); test(!menu.settings.localLights && !menu.settings.shadows && !menu.settings.lighting && menu.changed,"stick toggles local lights independently"); release();
  in.x=1; step(); test(menu.settings.localLights && !menu.settings.lighting && !menu.settings.shadows,"local lights preference can remain on in unlit mode"); release();
  menu.selected=3; in.a=true; step(); test(!menu.settings.frameOverlap && menu.changed,"CPU/GPU overlap comparison toggles independently"); release();
  std::ostringstream overlapIni; menu.settings.write(overlapIni); Vr::Settings overlapRestored; std::istringstream overlapInput(overlapIni.str()); overlapRestored.read(overlapInput);
  test(!overlapRestored.frameOverlap,"CPU/GPU overlap preference persists");
  menu.selected=4; in.a=true; step();
  test(!menu.settings.tiledLights && menu.changed && !menu.settings.frameOverlap && menu.settings.localLights,"tiled lights toggle independently"); release();
  std::ostringstream tiledIni; menu.settings.write(tiledIni); Vr::Settings tiledRestored; std::istringstream tiledInput(tiledIni.str()); tiledRestored.read(tiledInput);
  test(!tiledRestored.tiledLights,"tiled lighting preference persists");
  menu.selected=5; in.a=true; step();
  test(!menu.settings.subgroupTiles && menu.settings.stereoSeed && menu.changed,"subgroup light tiles can be compared independently");
  step(); test(!menu.settings.subgroupTiles && !menu.changed,"held accept cannot repeatedly change subgroup tiles"); release();
  menu.selected=6; in.a=true; step();
  test(!menu.settings.uniformLights && menu.settings.stereoSeed && menu.changed,"uniform light access toggles independently");
  step(); test(!menu.settings.uniformLights && !menu.changed,"held accept cannot retoggle uniform lights"); release();
  menu.selected=7; in.trigger=1; step();
  test(!menu.settings.stereoSeed && !menu.settings.subgroupTiles && menu.changed,"shared depth seed toggles independently"); release();
  std::ostringstream sharedIni; menu.settings.write(sharedIni); Vr::Settings sharedRestored; std::istringstream sharedInput(sharedIni.str()); sharedRestored.read(sharedInput);
  test(!sharedRestored.subgroupTiles && !sharedRestored.uniformLights && !sharedRestored.stereoSeed && !sharedRestored.shadows,"shared settings and existing shadow choice persist");
  menu.selected=8; in.a=true; step();
  test(!menu.settings.framePipeline && !menu.settings.stereoSeed && menu.changed,"frame pipeline toggles independently");
  step(); test(!menu.settings.framePipeline && !menu.changed,"held accept cannot retoggle pipeline"); release();
  std::ostringstream pipelineIni; menu.settings.write(pipelineIni); Vr::Settings pipelineRestored; std::istringstream pipelineInput(pipelineIni.str()); pipelineRestored.read(pipelineInput);
  test(!pipelineRestored.framePipeline && !pipelineRestored.shadows,"pipeline preference persists without changing shadows");
  menu.selected=9; in.a=true; step();
  test(menu.row()==Vr::Menu::CpuStaging && !menu.settings.cpuStaging && !menu.settings.framePipeline && menu.changed,"CPU staging toggles independently");
  step();test(!menu.settings.cpuStaging && !menu.changed,"held accept cannot retoggle CPU staging");release();
  std::ostringstream stageIni;menu.settings.write(stageIni);Vr::Settings stageRestored;std::istringstream stageInput(stageIni.str());stageRestored.read(stageInput);
  test(!stageRestored.cpuStaging && !stageRestored.framePipeline,"CPU staging preference persists independently");
  std::istringstream invalidStage("CpuStaging=nan\n");stageRestored.read(invalidStage);test(!stageRestored.cpuStaging,"invalid CPU staging preference is ignored");
  std::istringstream enableStage("CpuStaging=1\n");stageRestored.read(enableStage);test(stageRestored.cpuStaging&&!stageRestored.framePipeline,"CPU staging can be restored independently");
  menu.selected=10;in.a=true;step();
  test(menu.row()==Vr::Menu::LightDepth && !menu.settings.lightDepth && !menu.settings.tiledLights && menu.changed,"Light depth toggles without changing tiled lighting");
  step();test(!menu.settings.lightDepth && !menu.changed,"held input cannot retoggle light depth");release();
  std::ostringstream depthIni;menu.settings.write(depthIni);Vr::Settings depthRestored;std::istringstream depthInput(depthIni.str());depthRestored.read(depthInput);
  test(!depthRestored.lightDepth && !depthRestored.tiledLights && !depthRestored.shadows,"Light depth and existing graphics preferences persist");
  menu.selected=11;in.a=true;step();
  test(menu.row()==Vr::Menu::MergedTransparency && !menu.settings.mergedTransparency && !menu.settings.lightDepth && menu.changed,"Transparent pass merge toggles independently");
  step();test(!menu.settings.mergedTransparency && !menu.changed,"held input cannot retoggle merge");release();
  std::ostringstream mergeIni;menu.settings.write(mergeIni);Vr::Settings mergeRestored;std::istringstream mergeInput(mergeIni.str());mergeRestored.read(mergeInput);
  test(!mergeRestored.mergedTransparency && !mergeRestored.lightDepth && !mergeRestored.shadows,"Merge and existing graphics preferences persist");
  in.y=1; step(); release();
  test(menu.row()==Vr::Menu::SlabLights && menu.settings.slabLights && !menu.changed,"Light slabs row follows merge transparent");
  in.a=true; step();
  test(menu.row()==Vr::Menu::SlabLights && !menu.settings.slabLights && !menu.settings.mergedTransparency && menu.changed,"Light slabs toggles independently");
  step(); test(!menu.settings.slabLights && !menu.changed,"held input cannot retoggle light slabs"); release();
  std::ostringstream slabIni; menu.settings.write(slabIni); Vr::Settings slabRestored; std::istringstream slabInput(slabIni.str()); slabRestored.read(slabInput);
  test(!slabRestored.slabLights && !slabRestored.mergedTransparency && !slabRestored.lightDepth && !slabRestored.shadows,"Light slabs and existing graphics preferences persist");
  in.a=true; step(); test(menu.settings.slabLights && menu.changed,"Light slabs restores"); release();
  menu.selected=13;in.a=true;step();
  test(menu.page==Vr::Menu::Page::Performance && menu.row()==Vr::Menu::RenderTests && menu.visible && !menu.changed,"Back row returns to Render tests parent row");
  step(); test(menu.page==Vr::Menu::Page::Performance,"held Back accept cannot reopen tests"); release();
  in.a=true; step(); release(); in.b=true; step();
  test(menu.page==Vr::Menu::Page::Performance && menu.row()==Vr::Menu::RenderTests && menu.visible,"B returns to performance without closing menu");
  step(); test(menu.page==Vr::Menu::Page::Performance,"held B cannot skip parent page"); release();
  in.b=true; step(); test(menu.page==Vr::Menu::Page::Main && menu.row()==Vr::Menu::Performance,"nested menu returns to correct root row"); release();
  {
    // Performance -> Live profiler: Off / Panel / Compact /
    // CSV only on the same row, index 2, so no other row index moves.
    Vr::Menu pm; Vr::Input pin; pin.focused=true; uint64_t pnow=0;
    auto pstep=[&] { pnow+=20; return pm.update(pin,pnow); };
    auto prelease=[&] { pin={}; pin.focused=true; pstep(); };
    pstep(); pin.leftGrip=pin.rightGrip=pin.menu=true; pstep(); prelease();
    pm.selected=2; pin.a=true; pstep(); prelease();
    test(pm.page==Vr::Menu::Page::Performance && pm.rows().size()==18,"performance page keeps its 18 rows");
    pm.selected=2; test(pm.row()==Vr::Menu::Profiler,"profiler row keeps index 2");
    test(pm.settings.profiler && pm.settings.profilerView==0,"default profiler display is the panel");
    pin.x=1; pstep(); test(pm.settings.profiler && pm.settings.profilerView==1 && pm.changed,"panel -> compact"); prelease();
    pin.x=1; pstep(); test(pm.settings.profiler && pm.settings.profilerView==2 && pm.changed,"compact -> CSV only"); prelease();
    pin.x=1; pstep(); test(!pm.settings.profiler && pm.changed,"CSV only -> off"); prelease();
    pin.x=-1; pstep(); test(pm.settings.profiler && pm.settings.profilerView==2,"off steps back to CSV only"); prelease();
    pin.a=true; pstep(); test(!pm.settings.profiler,"A steps forward to off"); prelease();
    pin.a=true; pstep(); test(pm.settings.profiler && pm.settings.profilerView==0,"A from off opens the panel"); prelease();
    pin.x=1; pstep(); prelease();
    std::ostringstream pini; pm.settings.write(pini); Vr::Settings prestored; std::istringstream pinput(pini.str()); prestored.read(pinput);
    test(prestored.profiler && prestored.profilerView==1 && pini.str().find("ProfilerView=1\n")!=std::string::npos,"profiler display persists");
    Vr::Settings plegacy; std::istringstream plegacyIni("Profiler=1\n"); plegacy.read(plegacyIni);
    test(plegacy.profiler && plegacy.profilerView==0,"old INI keeps the panel");
    std::istringstream pbad("ProfilerView=9\n"); plegacy.read(pbad); test(plegacy.profilerView==2,"out-of-range profiler display clamps");
  }
  Vr::Settings bad; std::istringstream badInput("HudX=999\nHudY=nan\nFogMode=999\nGpuSampling=-20\n"); bad.read(badInput);
  close(bad.hudX,0.3f,"HUD offset bounded"); close(bad.hudY,0,"invalid HUD offset ignored");
  test(bad.fogMode==1&&bad.gpuSampling==0,"performance settings bounded");
  settings.shadows=false; settings.lighting=false; settings.localLights=false;
  settings.indexedObjects=false; settings.batchedObjects=false; settings.fastLighting=false; settings.hudX=0.15f; settings.hudY=-0.1f; settings.fogMode=1; settings.gpuSampling=2;
  std::ostringstream newer; settings.write(newer); std::istringstream reread(newer.str()); restored.read(reread);
  close(restored.hudX,0.15f,"HUD X persists"); close(restored.hudY,-0.1f,"HUD Y persists");
  test(!restored.shadows && !restored.lighting && !restored.localLights,"all render test switches persist");
  test(newer.str().find("Shadows=0\n")!=std::string::npos && newer.str().find("Lighting=0\n")!=std::string::npos && newer.str().find("LocalLights=0\n")!=std::string::npos,"render test INI keys are explicit");
  std::istringstream enableShadows("Shadows=1\n"); restored.read(enableShadows);
  test(restored.shadows && !restored.lighting && !restored.localLights,"reading shadows preserves other switches");
  std::istringstream enableLighting("Lighting=1\n"); restored.read(enableLighting);
  test(restored.shadows && restored.lighting && !restored.localLights,"reading lighting preserves local lights");
  std::istringstream enableLocalLights("LocalLights=1\n"); restored.read(enableLocalLights);
  test(restored.shadows && restored.lighting && restored.localLights,"all render passes can be restored");
  std::istringstream invalidRender("Shadows=nan\nLighting=inf\nLocalLights=bad\n"); restored.read(invalidRender);
  test(restored.shadows && restored.lighting && restored.localLights,"invalid render values leave rendering enabled");
  test(!restored.indexedObjects,"indexed geometry setting persists");
  test(!restored.batchedObjects && newer.str().find("BatchedObjects=0\n")!=std::string::npos,"batching comparison persists in separate INI key");
  std::istringstream batchOn("BatchedObjects=1\n"); restored.read(batchOn);
  test(restored.batchedObjects && !restored.indexedObjects,"reading batching preserves indexed setting");
  std::istringstream batchInvalid("BatchedObjects=nan\n"); restored.read(batchInvalid);
  test(restored.batchedObjects,"invalid batching setting is ignored");
  test(!restored.fastLighting,"lighting comparison persists");
  test(restored.fogMode==1&&restored.gpuSampling==2,"performance configuration persists");
  Vr::FrameStats baseline, comparison;
  test(baseline.sameConfiguration(comparison),"equal renderer configurations can share averages");
  for(auto member:{&Vr::FrameStats::slabLights,&Vr::FrameStats::directOutput,&Vr::FrameStats::mergedTransparency,&Vr::FrameStats::lightDepth,&Vr::FrameStats::shadows,&Vr::FrameStats::lighting,&Vr::FrameStats::localLights,&Vr::FrameStats::indexedObjects,&Vr::FrameStats::batchedObjects,&Vr::FrameStats::fastLighting,&Vr::FrameStats::tiledLights,&Vr::FrameStats::subgroupTiles,&Vr::FrameStats::uniformLights,&Vr::FrameStats::stereoSeed,&Vr::FrameStats::framePipeline}) {
    comparison=baseline; comparison.*member=!(baseline.*member);
    test(!baseline.sameConfiguration(comparison) && !comparison.sameConfiguration(baseline),"different render switches cannot share averages");
  }
  const auto previousPath=std::filesystem::current_path();
  const auto csvDir=previousPath/"build/tests/vrcontrols"/("profile-"+std::to_string(uint64_t(std::chrono::system_clock::now().time_since_epoch().count())));
  std::filesystem::create_directories(csvDir); std::filesystem::current_path(csvDir);
  {
    Vr::Profiler profiler;
    profiler.begin(true,2,0,1,false,true,true,false,true,false,true,false);
    test(!profiler.current.batchedObjects && profiler.current.indexedObjects,"profiler captures independent batching comparison");
    test(!profiler.current.shadows && profiler.current.lighting && !profiler.current.localLights,"profiler captures render switch values");
    profiler.finish();
    profiler.begin(true,2,0,1,false,true,true,false,true,false,true,false);
    profiler.current.tiledLights=false; profiler.current.slabLights=false; profiler.current.slabLightsActive={true,false}; profiler.current.subgroupTiles=false; profiler.current.uniformLights=false; profiler.current.stereoSeed=false; profiler.current.framePipeline=false; profiler.current.pipelineActive=false; profiler.current.priorGpuWait=1.375; profiler.current.uploadParts[0][2]=1.125; profiler.current.uploadParts[1][2]=0.125;
    profiler.current.tick=1.25; profiler.current.animation=2.5; profiler.current.camera=0.125; profiler.current.room=0.25;
    struct Timing { const char* name; double milliseconds; };
    profiler.eyeGpu(0,std::array{Timing{"Test pass",1.5}});
    profiler.finish();
    profiler.begin(false,2,0,1,false);
  }
  int csvFiles=0;
  for(const auto& entry:std::filesystem::directory_iterator(csvDir)) {
    if(entry.path().extension()!=".csv") continue;
    ++csvFiles; std::ifstream file(entry.path()); std::string header,row; std::getline(file,header); std::getline(file,row);
    auto cell=[&](const char* key) {
      std::istringstream names(header), values(row); std::string name,value;
      while(std::getline(names,name,',')) { if(!std::getline(values,value,',')) return std::string(); if(name==key) return value; }
      return std::string();
    };
    test(cell("tiled_lights")=="0","both CSVs record tiled-light mode");
    test(cell("slab_lights")=="0" && cell("left_slab_lights_active")=="1" && cell("right_slab_lights_active")=="0","both CSVs record requested and actual light slabs per eye");
    test(cell("batched_objects")=="0" && cell("indexed_objects")=="1","both CSVs attribute independent batching setting");
    test(cell("subgroup_tiles")=="0" && cell("uniform_lights")=="0" && cell("stereo_seed")=="0","both CSVs record subgroup and stereo preparation modes");
    test(cell("frame_pipeline")=="0" && cell("pipeline_active")=="0" && cell("prior_gpu_wait_ms")=="1.375","both CSVs record requested/actual pipeline and prior GPU drain");
    test(cell("shadows")=="0" && cell("lighting")=="1" && cell("local_lights")=="0","both CSVs preserve independent render configuration");
    if(entry.path().filename().string().starts_with("vr-profile-")) {
      test(cell("left_instances_upload_ms")=="1.125" && cell("right_instances_upload_ms")=="0.125","CPU upload details are recorded per eye");
      test(cell("tick_ms")=="1.25" && cell("animation_ms")=="2.5" && cell("camera_ms")=="0.125" && cell("room_ms")=="0.25","frame CSV separates CPU simulation stages");
    }
  }
  test(csvFiles==2,"frame and GPU pass CSVs both verified");
  std::filesystem::current_path(previousPath);
  Vr::Turning turn; Vr::Settings t;
  close(turn.update(1,true,t,0.02f),0,"turn requires neutral on entry"); turn.update(0,true,t,0.02f);
  close(turn.update(1,true,t,0.02f),-30,"right snap"); close(turn.update(1,true,t,0.02f),0,"held snap blocked");
  turn.update(0,true,t,0.02f); t.snapAngle=45; close(turn.update(-1,true,t,0.02f),45,"configured snap angle");
  turn.update(0,false,t,0.02f); close(turn.update(-1,true,t,0.02f),0,"turn blocked on focus gain");
  t.turn=Vr::TurnMode::Smooth; t.smoothSpeed=90;
  float total=0; turn.update(0,true,t,0); for(int i=0;i<72;++i) total+=turn.update(1,true,t,1.f/72.f);
  close(total,-90,"smooth speed independent of frame rate");
  close(turn.update(0.1f,true,t,0.02f),0,"smooth dead zone");
  t.turn=Vr::TurnMode::Physical; close(turn.update(1,true,t,0.02f),0,"physical mode ignores stick");
  XrMath::Pose eye,ref; eye.position.x=-0.032f;
  close(XrMath::relative(eye,ref,50)[3][0],-1.6f,"world twice as large halves virtual IPD");
  eye.position={0.2f,0,-0.1f}; auto room=XrMath::relative(eye,ref,50);
  close(room[3][0],10,"room distance follows world scale"); close(room[3][2],-5,"forward room coordinate");
  Vr::RoomMotion motion;
  motion.delta({},true);
  close(motion.delta({0.2f,0,0},true).x,0.2f,"physical displacement reaches collision mover");
  motion.consume({0.2f,0,0});
  close(motion.correction({0.2f,0,0},100).x,20,"body displacement removed from eye only once");
  close(motion.delta({0.2f,0,0},false).length(),0,"VR menu pauses body motion");
  close(motion.correction({0.2f,0,0},100).x,20,"opening VR menu cannot shift camera after room walk");
  close(motion.correction({0.25f,0,0},100).x,20,"head translation still tracked while VR menu open");
  close(motion.delta({0.25f,0,0},true).x,0.05f,"resume reconciles physical menu movement");
  motion.consume({0.05f,0,0});
  motion.delta({0.45f,0,0},true); motion.consume({0.05f,0,0});
  close(motion.blocked({0.45f,0,0},100),15,"partial collision retains blocked displacement");
  close(45-motion.correction({0.45f,0,0},100).x,8,"wall bounds camera lean");
  close(motion.delta({0.44f,0,0},true).x,0.14f,"wall retreat cannot re-anchor through collision");
  close(motion.delta({0.30f,0,0},true).length(),0,"physical return to body clears pending motion");
  close(motion.delta({2,0,0},true).length(),0,"tracking discontinuity cannot teleport body");
  motion.reset(); close(motion.correction({},100).length(),0,"recenter clears old physical offset");
  Vr::Welcome welcome;
  test(!welcome.update(false,true,true,0) && !welcome.shown,"loading and title movement cannot consume the welcome");
  test(!welcome.update(true,true,false,0),"welcome waits for the first movement request");
  test(welcome.update(true,true,true,1) && welcome.visible,"first movement opens welcome even with a held button");
  test(welcome.update(true,true,true,1) && welcome.visible,"held opening button cannot dismiss welcome");
  test(welcome.update(true,true,true,0) && welcome.visible,"stick movement alone cannot dismiss welcome");
  test(welcome.update(true,false,false,2) && welcome.visible,"focus loss cannot dismiss welcome");
  welcome.update(true,true,false,0);
  test(welcome.update(true,true,true,2) && !welcome.visible,"fresh button dismisses and is consumed");
  test(welcome.update(true,true,true,2) && !welcome.visible,"held dismissal cannot leak a grip or trigger to gameplay");
  welcome.update(true,true,true,0);
  test(!welcome.update(true,true,true,0) && !welcome.visible,"acknowledged welcome cannot reopen");
  Vr::Settings speed;speed.welcomeSeen=true;speed.runSpeed=1.65f;std::ostringstream speedOut;speed.write(speedOut);Vr::Settings speedIn;std::istringstream speedStream(speedOut.str());speedIn.read(speedStream);
  test(speedIn.welcomeSeen,"welcome acknowledgement persists across application launches");
  Vr::Welcome restarted;restarted.shown=speedIn.welcomeSeen;
  test(!restarted.update(true,true,true,0) && !restarted.visible,"saved acknowledgement suppresses the next launch welcome");
  close(speedIn.runSpeed,1.65f,"run speed persists independently of movement mapping");
  speed.runSpeed=10;speed.sanitize();close(speed.runSpeed,2,"run speed has a two-times upper limit");
  speed.runSpeed=-1;speed.sanitize();close(speed.runSpeed,.75f,"running remains faster than baseline walk");
  std::printf("PASS %d VR settings, menu, turning and scale checks\n",checks);
}
