#version 460
#extension GL_GOOGLE_include_directive : enable

#include "scene.glsl"
#include "common.glsl"
#include "half_resolution.glsl"

layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0) uniform writeonly image2D result;
layout(binding = 1, std140) uniform UboScene {
  SceneDesc scene;
  };
layout(binding = 2) uniform sampler2D aoDepth;
layout(binding = 3) uniform sampler2D depthBuf;

void main() {
  const ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
  if(any(greaterThanEqual(pixel, imageSize(result))))
    return;
  const float z = texelFetch(depthBuf, pixel, 0).r;
  const float ao = z>=1.0 ? 1.0 : ssaoResolveHalf(aoDepth, pixel, linearDepth(z, scene.clipInfo));
  imageStore(result, pixel, vec4(ao));
  }
