"""Compile and run asset-free VR host regressions from this source kit.

Requires Python 3.10+ and a C++20 compiler. For MSVC, use an x64 Developer
Command Prompt. Optional --output keeps a fresh run directory and JSON report;
otherwise temporary compiler/test files are removed automatically.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]


def source_checks() -> list[str]:
    cmake = (ROOT / 'android/CMakeLists.txt').read_text(encoding='utf-8')
    xr = (ROOT / 'engine/common/vr/questxr.cpp').read_text(encoding='utf-8')
    apk_version = re.search(r'\bVERSION_CODE\s+(\d+)\b', cmake)
    xr_version = re.search(r'applicationInfo\.applicationVersion\s*=\s*(\d+)', xr)
    if not apk_version or not xr_version or apk_version[1] != xr_version[1]:
        raise RuntimeError('OpenXR application version must match the APK VERSION_CODE')
    gameplay = (ROOT / 'engine/common/vr/vrgameplay.cpp').read_text(encoding='utf-8')
    roof_update = 'if(now>=roofCheck || (body.head-roofPosition).length()>100.f)'
    if gameplay.count(roof_update) != 1:
        raise RuntimeError('Expected one rain/roof cache update in Gameplay::update')
    placeholder = re.compile(
        r'\b(?:chatgpt|as an ai|insert (?:your )?code here|'
        r'placeholder implementation|todo implement|generated by (?:an )?ai)\b', re.I)
    for path in (ROOT / 'engine/common/vr').iterdir():
        if path.suffix not in {'.h', '.cpp'}:
            continue
        if placeholder.search(path.read_text(encoding='utf-8')):
            raise RuntimeError(f'Assistant/placeholder phrase needs review: {path.relative_to(ROOT)}')
    return ['OpenXR/APK version alignment', 'single rain/roof cache update',
            'no obvious assistant placeholder phrases in VR source']


def execute(command: list[str], cwd: Path) -> str:
    process = subprocess.run(command, cwd=cwd, text=True, encoding='utf-8',
                             errors='replace', stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT, timeout=180)
    if process.returncode:
        raise RuntimeError(f'Command failed ({process.returncode}): {command[0]}\n{process.stdout}')
    return process.stdout.strip()


def run(args: argparse.Namespace, output: Path) -> dict:
    checks = source_checks()
    for check in checks:
        print(f'PASS: {check}', flush=True)
    compiler = args.cxx or os.environ.get('CXX')
    if not compiler:
        candidates = ('cl', 'clang++', 'g++', 'c++') if os.name == 'nt' else ('c++', 'clang++', 'g++')
        compiler = next((shutil.which(name) for name in candidates if shutil.which(name)), None)
    if not compiler:
        raise RuntimeError('C++20 compiler missing. Use an x64 MSVC Developer Command Prompt, '
                           'put a compiler on PATH, or pass --cxx /path/to/compiler.')
    msvc = Path(compiler).name.lower() in {'cl', 'cl.exe', 'clang-cl', 'clang-cl.exe'}
    common = ROOT / 'engine/common'
    tempest = ROOT / 'engine/lib/Tempest/Engine'
    matrix = tempest / 'math/matrix.cpp'
    suites = [
        ('release-defaults', 'release-defaults.cpp', None, [matrix], []),
        ('xrmath', 'xrmath.cpp', None, [matrix], []),
        ('vrcontrols', 'vrcontrols.cpp', None, [matrix], []),
        ('menu-shortcuts', 'menu-shortcuts.cpp', None, [matrix], []),
        ('menu-input', 'menu-input.cpp', 'menu-input.py', [common / 'utils/gamepadbindings.cpp', matrix], []),
        ('vrinteraction', 'vrinteraction.cpp', None,
         [common / 'utils/gamepadbindings.cpp', matrix], []),
        ('sky', 'sky.cpp', 'sky.py', [matrix], []),
        ('npc-attachments', 'npc.cpp', 'npc-attachments.py', [matrix], []),
        ('camera-yaw-pcvr', 'camera-yaw.cpp', 'camera-yaw.py', [], ['GOTHIC2VR_OPENXR']),
        ('camera-yaw-quest', 'camera-yaw.cpp', 'camera-yaw.py', [], ['GOTHIC2VR_OPENXR', '__ANDROID__']),
        ('camera-yaw-flat', 'camera-yaw.cpp', 'camera-yaw.py', [], []),
        ('camera-yaw-touch', 'camera-yaw.cpp', 'camera-yaw.py', [], ['__ANDROID__']),
        ('pcvr-regressions', 'pcvr-regressions.cpp', 'pcvr-regressions.py', [], ['GOTHIC2VR_OPENXR', 'GOTHIC2VR_MIRROR']),
        ('bow-regressions', 'regressions.cpp', 'bow-regressions.py', [matrix], []),
        ('grip-regressions', 'regressions.cpp', 'grip-regressions.py', [matrix], []),
        ('melee-regressions', 'regressions.cpp', 'melee-regressions.py', [matrix], []),
        ('hud-regressions', 'regressions.cpp', 'hud-regressions.py', [matrix], []),
        ('hud-extent', 'hud-extent.cpp', None, [], []),
        ('split-upload', 'split-upload.cpp', 'split-upload.py', [], []),
        ('swim-motion', 'swim-motion.cpp', None, [], []),
        ('locomotion-input', 'locomotion-input.cpp', None, [matrix], []),
        ('swim-integration', 'swim-integration.cpp', 'swim-integration.py', [matrix], []),
        ('camera-water', 'camera-water.cpp', 'camera-water.py', [matrix], []),
        ('swimming-hands', 'swimming-hands.cpp', 'swimming-hands.py', [], []),
        ('native-actions', 'actions.cpp', 'native-actions.py', [], []),
        ('calibration', 'calibration.cpp', 'calibration.py', [matrix], []),
        ('combat', 'combat.cpp', 'combat.py', [matrix], []),
        ('focus', 'focus.cpp', 'focus.py', [matrix], []),
        ('gameplay-regressions', 'regressions.cpp', 'gameplay-regressions.py',
         [matrix], ['GOTHIC2VR_OPENXR']),
    ]
    results = []
    for name, filename, generator, extra, defines in suites:
        directory = output / name
        directory.mkdir()
        if generator:
            execute([sys.executable, str(ROOT / 'tests' / generator), str(directory)], output)
            source = directory / filename
        else:
            source = ROOT / 'tests' / filename
        executable = directory / (name + ('.exe' if os.name == 'nt' else ''))
        includes = [common, tempest / 'include']
        defines = ['_USE_MATH_DEFINES', *defines]
        if msvc:
            command = [compiler, '/nologo', '/std:c++20', '/EHsc', '/utf-8',
                       *[f'/I{path}' for path in includes], *[f'/D{name}' for name in defines],
                       str(source), *map(str, extra), f'/Fe:{executable}']
        else:
            command = [compiler, '-std=c++20', '-pthread',
                       *[f'-I{path}' for path in includes], *[f'-D{name}' for name in defines],
                       str(source), *map(str, extra), '-o', str(executable)]
        compile_log = execute(command, directory)
        test_log = execute([str(executable)], ROOT)
        (directory / 'compile.log').write_text(compile_log + '\n', encoding='utf-8')
        (directory / 'test.log').write_text(test_log + '\n', encoding='utf-8')
        print(test_log, flush=True)
        results.append({'suite': name, 'status': 'passed', 'output': test_log})
    return {'status': 'passed', 'source_checks': checks, 'compiler': compiler,
            'suites': results, 'game_assets_used': False, 'game_linked': False,
            'headset_validated': False}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cxx', help='C++20 compiler executable (also reads CXX)')
    parser.add_argument('--output', type=Path, help='keep logs and binaries in a fresh subdirectory here')
    args = parser.parse_args()
    temporary = None
    if args.output:
        args.output.mkdir(parents=True, exist_ok=True)
        output = Path(tempfile.mkdtemp(prefix='vr-host-', dir=args.output)).resolve()
    else:
        temporary = tempfile.TemporaryDirectory(prefix='gothic2vr-host-')
        output = Path(temporary.name)
    try:
        report = run(args, output)
        (output / 'report.json').write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
        print(f'PASS: {len(report["suites"])} freshly compiled host suites; no game or headset run.')
        if args.output:
            print(f'Report: {output / "report.json"}')
        return 0
    except (OSError, RuntimeError, subprocess.TimeoutExpired) as error:
        print(f'FAIL: {error}', file=sys.stderr)
        return 1
    finally:
        if temporary:
            temporary.cleanup()


if __name__ == '__main__':
    raise SystemExit(main())
